spring:
  application:
    name: account-manager
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/Desktop/db/accountdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true